server:
  port: 8090
  use-forward-headers: true
  compression:
    enabled: false
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    # H2 Database 配置
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/Atomic-test/db/Atomic
    username: admin
    password: 123456

    # MySQL 配置
  #  driver-class-name: com.mysql.cj.jdbc.Driver
  #  url: jdbc:mysql://127.0.0.1:3306/Atomicdb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  #  username: root
  #  password: 123456

  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    favicon:
      enabled: false
  cache:
    type: none
logging:
  level:
    run.atomic.app: DEBUG
    org.hibernate: ERROR
  path: ${user.home}/Atomic-test/logs

Atomic:
  doc-disabled: false
