server:
  port: 443
  use-forward-headers: true
  compression:
    enabled: false
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
  ssl:
    key-store: classpath:cert/3105303_atomical.ltd.pfx
    key-store-password: i8gsx1RF
    key-store-type: PKCS12
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    add-properties: false
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    # H2 Database 配置
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/.Atomic/db/Atomic
#    username: admin
#    password: 123456

    # MySQL 配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123qwe

  h2:
    console:
      settings:
        web-allow-others: false
      path: /h2-console
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  mvc:
    favicon:
      enabled: false
logging:
  level:
    run.atomic.app: INFO
  path: ${user.home}/.atomic/logs